### ISSUE TITLE
WebSocket Support

### ISSUE THREAD

**Issue by swizzlr** [bermudadigitalstudio/titan-core#2]
Titan currently processes HTTP requests and responses. Semantically, WebSockets do not fit into this model – it is a stream that can be processed, mapped, filtered and responded to. The function is meant to return a response – if it blocks forever on an upgraded stream, that could break the concurrency assumptions of WebServers.

- WebSocket support is something for the server to handle (currently what we do)
- WS support is something that we special case in Titan (increases complexity)
- WS support is something we hack into middleware support (no)

I'm very much inclined to keep things the way they are; please re-open this issue and discuss if you feel you have anything to add.

**Comment by skreutzberger** [comment]
Maybe we can orient on what Slack did in terms of websockets format, source code and documentation:

- [https://api.slack.com/rtm](https://api.slack.com/rtm)
- [https://github.com/pvzig/SlackKit/tree/linux](https://github.com/pvzig/SlackKit/tree/linux)
